/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica.registrardictamen;

/**
 *
 * @author Alberto Sánchez
 */
public class VentanaRegistrarDictamen extends javax.swing.JFrame {

  /**
   * Creates new form VentanaRegistrarDictamen
   */
  public VentanaRegistrarDictamen() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jPanelRegistrarDictamen = new javax.swing.JPanel();
    jLabelEtiquetaRegresar1 = new javax.swing.JLabel();
    jLabelRegresar1 = new javax.swing.JLabel();
    jLabelLogoCc = new javax.swing.JLabel();
    jLabelEtiquetaRegistrarDictamen = new javax.swing.JLabel();
    jPanelInformacionSolicitante = new javax.swing.JPanel();
    jLabelTipoDictamen = new javax.swing.JLabel();
    jLabelTipoMantenimiento = new javax.swing.JLabel();
    jComboBoxTipoDictamen = new javax.swing.JComboBox<>();
    jComboBoxTipoMantenimiento = new javax.swing.JComboBox<>();
    jPanelInformacionDispositivo = new javax.swing.JPanel();
    jLabelTipoEquipo = new javax.swing.JLabel();
    jLabelNumeroinventario = new javax.swing.JLabel();
    jComboBoxNumeroInventario = new javax.swing.JComboBox<>();
    jLabelTipoBorrado = new javax.swing.JLabel();
    jLabelPartesDispositivo = new javax.swing.JLabel();
    jLabelEstadoDispositivo = new javax.swing.JLabel();
    jLabelModelo = new javax.swing.JLabel();
    jLabelMarca = new javax.swing.JLabel();
    jTextFieldTipoEquipo = new javax.swing.JTextField();
    jTextFieldModelo = new javax.swing.JTextField();
    jTextFieldMarca = new javax.swing.JTextField();
    jComboBoxPartesDispositivo = new javax.swing.JComboBox<>();
    jComboBoxEstadoDispositivo = new javax.swing.JComboBox<>();
    jComboBoxTipoBorrado = new javax.swing.JComboBox<>();
    jPanelInformacionTabla = new javax.swing.JPanel();
    jLabelTipoFalla = new javax.swing.JLabel();
    jComboBoxTipoFalla = new javax.swing.JComboBox<>();
    jLabelDescripcionProblema = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextAreaDescipcionProblema = new javax.swing.JTextArea();
    jPanelDetalleDictamen = new javax.swing.JPanel();
    jLabelObservaciones = new javax.swing.JLabel();
    jLabelDescripcionDictamen = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextAreaDescipcionDictamen = new javax.swing.JTextArea();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTextAreaObservacionesEquipo = new javax.swing.JTextArea();
    jButtonRegistrar = new javax.swing.JButton();

    jLabel1.setText("jLabel1");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanelRegistrarDictamen.setBackground(new java.awt.Color(255, 255, 255));

    jLabelEtiquetaRegresar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabelEtiquetaRegresar1.setText("Regresar");

    jLabelRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazgrafica/imagenes/LabelBack.png"))); // NOI18N

    jLabelLogoCc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazgrafica/imagenes/LabelLogoPequeñoCc.png"))); // NOI18N

    jLabelEtiquetaRegistrarDictamen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabelEtiquetaRegistrarDictamen.setText("Registrar Dictamen");

    jLabelTipoDictamen.setText("Tipo de dictamen: ");

    jLabelTipoMantenimiento.setText("Tipo de mantenimiento:");

    jComboBoxTipoDictamen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jComboBoxTipoMantenimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout jPanelInformacionSolicitanteLayout = new javax.swing.GroupLayout(jPanelInformacionSolicitante);
    jPanelInformacionSolicitante.setLayout(jPanelInformacionSolicitanteLayout);
    jPanelInformacionSolicitanteLayout.setHorizontalGroup(
      jPanelInformacionSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelInformacionSolicitanteLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabelTipoDictamen)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jComboBoxTipoDictamen, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(36, 36, 36)
        .addComponent(jLabelTipoMantenimiento)
        .addGap(30, 30, 30)
        .addComponent(jComboBoxTipoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanelInformacionSolicitanteLayout.setVerticalGroup(
      jPanelInformacionSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelInformacionSolicitanteLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelInformacionSolicitanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelTipoDictamen)
          .addComponent(jLabelTipoMantenimiento)
          .addComponent(jComboBoxTipoDictamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jComboBoxTipoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabelTipoEquipo.setText("Tipo de equipo:");

    jLabelNumeroinventario.setText("Numero inventario:");

    jComboBoxNumeroInventario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jLabelTipoBorrado.setText("Tipo de borrado:");

    jLabelPartesDispositivo.setText("Partes de dispositivo:");

    jLabelEstadoDispositivo.setText("Estado de dispositivo:");

    jLabelModelo.setText("Modelo:");

    jLabelMarca.setText("Marca:");

    jTextFieldMarca.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jTextFieldMarcaActionPerformed(evt);
      }
    });

    jComboBoxPartesDispositivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jComboBoxEstadoDispositivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
    jComboBoxEstadoDispositivo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jComboBoxEstadoDispositivoActionPerformed(evt);
      }
    });

    jComboBoxTipoBorrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout jPanelInformacionDispositivoLayout = new javax.swing.GroupLayout(jPanelInformacionDispositivo);
    jPanelInformacionDispositivo.setLayout(jPanelInformacionDispositivoLayout);
    jPanelInformacionDispositivoLayout.setHorizontalGroup(
      jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelInformacionDispositivoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabelMarca)
          .addComponent(jLabelModelo)
          .addGroup(jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTipoEquipo)
            .addComponent(jLabelTipoBorrado)))
        .addGap(18, 18, 18)
        .addGroup(jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanelInformacionDispositivoLayout.createSequentialGroup()
            .addGroup(jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(jPanelInformacionDispositivoLayout.createSequentialGroup()
                .addGroup(jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanelInformacionDispositivoLayout.createSequentialGroup()
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGroup(jPanelInformacionDispositivoLayout.createSequentialGroup()
                    .addComponent(jComboBoxTipoBorrado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(42, 42, 42)))
                .addGroup(jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabelPartesDispositivo, javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jLabelEstadoDispositivo, javax.swing.GroupLayout.Alignment.TRAILING)))
              .addGroup(jPanelInformacionDispositivoLayout.createSequentialGroup()
                .addComponent(jTextFieldTipoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNumeroinventario)))
            .addGap(34, 34, 34)
            .addGroup(jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jComboBoxNumeroInventario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jComboBoxPartesDispositivo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jComboBoxEstadoDispositivo, 0, 103, Short.MAX_VALUE))
            .addGap(43, 43, 43))
          .addGroup(jPanelInformacionDispositivoLayout.createSequentialGroup()
            .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    jPanelInformacionDispositivoLayout.setVerticalGroup(
      jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelInformacionDispositivoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelTipoEquipo)
          .addComponent(jLabelNumeroinventario)
          .addComponent(jComboBoxNumeroInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jTextFieldTipoEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelTipoBorrado)
          .addComponent(jLabelPartesDispositivo)
          .addComponent(jComboBoxPartesDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jComboBoxTipoBorrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelEstadoDispositivo)
          .addComponent(jLabelModelo)
          .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jComboBoxEstadoDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanelInformacionDispositivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelMarca)
          .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jLabelTipoFalla.setText("Tipo de falla:");

    jComboBoxTipoFalla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jLabelDescripcionProblema.setText("Descipción del problema:");

    jTextAreaDescipcionProblema.setColumns(20);
    jTextAreaDescipcionProblema.setRows(5);
    jScrollPane1.setViewportView(jTextAreaDescipcionProblema);

    javax.swing.GroupLayout jPanelInformacionTablaLayout = new javax.swing.GroupLayout(jPanelInformacionTabla);
    jPanelInformacionTabla.setLayout(jPanelInformacionTablaLayout);
    jPanelInformacionTablaLayout.setHorizontalGroup(
      jPanelInformacionTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelInformacionTablaLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabelTipoFalla)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jComboBoxTipoFalla, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(303, 303, 303))
      .addGroup(jPanelInformacionTablaLayout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addComponent(jLabelDescripcionProblema)
        .addGap(31, 31, 31)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanelInformacionTablaLayout.setVerticalGroup(
      jPanelInformacionTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelInformacionTablaLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelInformacionTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelTipoFalla)
          .addComponent(jComboBoxTipoFalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(jPanelInformacionTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanelInformacionTablaLayout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addComponent(jLabelDescripcionProblema)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformacionTablaLayout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())))
    );

    jLabelObservaciones.setText("Observaciones del equipo:");

    jLabelDescripcionDictamen.setText("Descripción del dictamen:");

    jTextAreaDescipcionDictamen.setColumns(20);
    jTextAreaDescipcionDictamen.setRows(5);
    jScrollPane2.setViewportView(jTextAreaDescipcionDictamen);

    jTextAreaObservacionesEquipo.setColumns(20);
    jTextAreaObservacionesEquipo.setRows(5);
    jScrollPane3.setViewportView(jTextAreaObservacionesEquipo);

    javax.swing.GroupLayout jPanelDetalleDictamenLayout = new javax.swing.GroupLayout(jPanelDetalleDictamen);
    jPanelDetalleDictamen.setLayout(jPanelDetalleDictamenLayout);
    jPanelDetalleDictamenLayout.setHorizontalGroup(
      jPanelDetalleDictamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelDetalleDictamenLayout.createSequentialGroup()
        .addGap(68, 68, 68)
        .addComponent(jLabelObservaciones)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabelDescripcionDictamen)
        .addGap(80, 80, 80))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDetalleDictamenLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    jPanelDetalleDictamenLayout.setVerticalGroup(
      jPanelDetalleDictamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelDetalleDictamenLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelDetalleDictamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelObservaciones)
          .addComponent(jLabelDescripcionDictamen))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanelDetalleDictamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
    );

    jButtonRegistrar.setBackground(new java.awt.Color(54, 54, 93));
    jButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
    jButtonRegistrar.setText("Registrar actividad de mantenimiento");

    javax.swing.GroupLayout jPanelRegistrarDictamenLayout = new javax.swing.GroupLayout(jPanelRegistrarDictamen);
    jPanelRegistrarDictamen.setLayout(jPanelRegistrarDictamenLayout);
    jPanelRegistrarDictamenLayout.setHorizontalGroup(
      jPanelRegistrarDictamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelRegistrarDictamenLayout.createSequentialGroup()
        .addGroup(jPanelRegistrarDictamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanelRegistrarDictamenLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanelRegistrarDictamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanelRegistrarDictamenLayout.createSequentialGroup()
                .addComponent(jLabelRegresar1)
                .addGap(14, 14, 14)
                .addComponent(jLabelEtiquetaRegresar1)
                .addGap(124, 124, 124)
                .addComponent(jLabelLogoCc)
                .addGap(0, 0, Short.MAX_VALUE))
              .addComponent(jPanelInformacionSolicitante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jPanelInformacionDispositivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jPanelInformacionTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jPanelDetalleDictamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
          .addGroup(jPanelRegistrarDictamenLayout.createSequentialGroup()
            .addGap(203, 203, 203)
            .addComponent(jLabelEtiquetaRegistrarDictamen)
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
      .addGroup(jPanelRegistrarDictamenLayout.createSequentialGroup()
        .addGap(167, 167, 167)
        .addComponent(jButtonRegistrar)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanelRegistrarDictamenLayout.setVerticalGroup(
      jPanelRegistrarDictamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelRegistrarDictamenLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelRegistrarDictamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelRegresar1)
          .addComponent(jLabelEtiquetaRegresar1)
          .addComponent(jLabelLogoCc))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabelEtiquetaRegistrarDictamen)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanelInformacionSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanelInformacionDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanelInformacionTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPanelDetalleDictamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jButtonRegistrar)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelRegistrarDictamen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanelRegistrarDictamen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jTextFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMarcaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jTextFieldMarcaActionPerformed

  private void jComboBoxEstadoDispositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoDispositivoActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jComboBoxEstadoDispositivoActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonRegistrar;
  private javax.swing.JComboBox<String> jComboBoxEstadoDispositivo;
  private javax.swing.JComboBox<String> jComboBoxNumeroInventario;
  private javax.swing.JComboBox<String> jComboBoxPartesDispositivo;
  private javax.swing.JComboBox<String> jComboBoxTipoBorrado;
  private javax.swing.JComboBox<String> jComboBoxTipoDictamen;
  private javax.swing.JComboBox<String> jComboBoxTipoFalla;
  private javax.swing.JComboBox<String> jComboBoxTipoMantenimiento;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabelDescripcionDictamen;
  private javax.swing.JLabel jLabelDescripcionProblema;
  private javax.swing.JLabel jLabelEstadoDispositivo;
  private javax.swing.JLabel jLabelEtiquetaRegistrarDictamen;
  private javax.swing.JLabel jLabelEtiquetaRegresar1;
  private javax.swing.JLabel jLabelLogoCc;
  private javax.swing.JLabel jLabelMarca;
  private javax.swing.JLabel jLabelModelo;
  private javax.swing.JLabel jLabelNumeroinventario;
  private javax.swing.JLabel jLabelObservaciones;
  private javax.swing.JLabel jLabelPartesDispositivo;
  private javax.swing.JLabel jLabelRegresar1;
  private javax.swing.JLabel jLabelTipoBorrado;
  private javax.swing.JLabel jLabelTipoDictamen;
  private javax.swing.JLabel jLabelTipoEquipo;
  private javax.swing.JLabel jLabelTipoFalla;
  private javax.swing.JLabel jLabelTipoMantenimiento;
  private javax.swing.JPanel jPanelDetalleDictamen;
  private javax.swing.JPanel jPanelInformacionDispositivo;
  private javax.swing.JPanel jPanelInformacionSolicitante;
  private javax.swing.JPanel jPanelInformacionTabla;
  private javax.swing.JPanel jPanelRegistrarDictamen;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTextArea jTextAreaDescipcionDictamen;
  private javax.swing.JTextArea jTextAreaDescipcionProblema;
  private javax.swing.JTextArea jTextAreaObservacionesEquipo;
  private javax.swing.JTextField jTextFieldMarca;
  private javax.swing.JTextField jTextFieldModelo;
  private javax.swing.JTextField jTextFieldTipoEquipo;
  // End of variables declaration//GEN-END:variables
}
