/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica.menujefecentrocomputo;

import centrocomputo.interfaz.*;
import centrocomputo.inventario.*;
import interfazgrafica.administrarhardware.*;
import interfazgrafica.administrarresponsables.*;
import interfazgrafica.administrarusuarios.*;
import repositorio.dataaccesobject.*;
import repositorio.interfaz.*;

/**
 *
 * @author Alberto Sánchez
 */
public class VentanaMenuJefeCentroComputo extends javax.swing.JFrame {
  
  private static VentanaMenuJefeCentroComputo ventanaMenuJcc = null;
  InventarioUsuarioInterface inventarioUsuario;
  InventarioHardwareInterface inventarioHardware;
  InventarioResponsableInterface inventarioResponsable;
  String rolNecesario = "JCC";

  /**
   * Creates new form VentanaMenuJefeCentroComputo
   */

  public VentanaMenuJefeCentroComputo(InventarioUsuarioInterface inventarioUsuario) {
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanelMenuJefeCentroComputo = new javax.swing.JPanel();
    jLabelTituloVentana = new javax.swing.JLabel();
    jButtonAdministrarHardware = new javax.swing.JButton();
    jButtonAdministrarUsuarios = new javax.swing.JButton();
    jButtonAdministrarResponsables = new javax.swing.JButton();
    jLabelLogoCc = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanelMenuJefeCentroComputo.setBackground(new java.awt.Color(255, 255, 255));

    jLabelTituloVentana.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
    jLabelTituloVentana.setText("Jefe de Centro de Computo");

    jButtonAdministrarHardware.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButtonAdministrarHardware.setText("Administrar Hardware");
    jButtonAdministrarHardware.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButtonAdministrarHardwareMouseClicked(evt);
      }
    });

    jButtonAdministrarUsuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButtonAdministrarUsuarios.setText("Administrar Usuarios (TA)");
    jButtonAdministrarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButtonAdministrarUsuariosMouseClicked(evt);
      }
    });

    jButtonAdministrarResponsables.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jButtonAdministrarResponsables.setText("Administrar Responsables");
    jButtonAdministrarResponsables.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jButtonAdministrarResponsablesMouseClicked(evt);
      }
    });

    jLabelLogoCc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazgrafica/imagenes/LabelLogoCc.png"))); // NOI18N

    javax.swing.GroupLayout jPanelMenuJefeCentroComputoLayout = new javax.swing.GroupLayout(jPanelMenuJefeCentroComputo);
    jPanelMenuJefeCentroComputo.setLayout(jPanelMenuJefeCentroComputoLayout);
    jPanelMenuJefeCentroComputoLayout.setHorizontalGroup(
      jPanelMenuJefeCentroComputoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelMenuJefeCentroComputoLayout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addGroup(jPanelMenuJefeCentroComputoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabelLogoCc)
          .addComponent(jLabelTituloVentana))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
        .addGroup(jPanelMenuJefeCentroComputoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButtonAdministrarHardware, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButtonAdministrarUsuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButtonAdministrarResponsables, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(40, 40, 40))
    );
    jPanelMenuJefeCentroComputoLayout.setVerticalGroup(
      jPanelMenuJefeCentroComputoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelMenuJefeCentroComputoLayout.createSequentialGroup()
        .addGap(38, 38, 38)
        .addComponent(jLabelTituloVentana)
        .addGroup(jPanelMenuJefeCentroComputoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanelMenuJefeCentroComputoLayout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addComponent(jButtonAdministrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(37, 37, 37)
            .addComponent(jButtonAdministrarHardware, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(41, 41, 41)
            .addComponent(jButtonAdministrarResponsables, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanelMenuJefeCentroComputoLayout.createSequentialGroup()
            .addGap(40, 40, 40)
            .addComponent(jLabelLogoCc)))
        .addContainerGap(43, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelMenuJefeCentroComputo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelMenuJefeCentroComputo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonAdministrarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdministrarUsuariosMouseClicked
    despliegaVentanaAdministrarUsuarios();
  }//GEN-LAST:event_jButtonAdministrarUsuariosMouseClicked

  private void jButtonAdministrarHardwareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdministrarHardwareMouseClicked
    despliegaVentanaAdministrarHardware();
  }//GEN-LAST:event_jButtonAdministrarHardwareMouseClicked

  private void jButtonAdministrarResponsablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdministrarResponsablesMouseClicked
    despliegaVentanaAdministrarResponsables();
  }//GEN-LAST:event_jButtonAdministrarResponsablesMouseClicked

  private void despliegaVentanaAdministrarUsuarios(){
    AccesoDatosUsuarioInterface repositorioUsuario = new AccesoDatosUsuario();
    InventarioUsuarioInterface inventarioUsuario = InventarioUsuario.obtieneInstancia(repositorioUsuario);
    VentanaAdministrarUsuarios ventanaUsuarios 
            = new VentanaAdministrarUsuarios(this, inventarioUsuario);
    ventanaUsuarios.setLocationRelativeTo(null);
    ventanaUsuarios.setVisible(true);
    this.setVisible(false);
  }
  
  private void despliegaVentanaAdministrarHardware(){
    AccesoDatosHardwareInterface repositorioHardware = new AccesoDatosHardware();
    InventarioHardwareInterface inventarioHardware = InventarioHardware.obtieneInstancia(repositorioHardware);
    VentanaAdministrarHardware ventanaHardware 
            = new VentanaAdministrarHardware(this, inventarioHardware);
    ventanaHardware.setLocationRelativeTo(null);
    ventanaHardware.setVisible(true);
    this.setVisible(false);
  }
  
  private void despliegaVentanaAdministrarResponsables(){
    AccesoDatosResponsableInterface repositorioResponsable = new AccesoDatosResponsable();
    InventarioResponsableInterface inventarioResponsable = InventarioResponsable.obtieneInstancia(repositorioResponsable);
    VentanaAdministrarResponsables ventanaResponsables 
            = new VentanaAdministrarResponsables(this, inventarioResponsable);
    ventanaResponsables.setLocationRelativeTo(null);
    ventanaResponsables.setVisible(true);
    this.setVisible(false);
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAdministrarHardware;
  private javax.swing.JButton jButtonAdministrarResponsables;
  private javax.swing.JButton jButtonAdministrarUsuarios;
  private javax.swing.JLabel jLabelLogoCc;
  private javax.swing.JLabel jLabelTituloVentana;
  private javax.swing.JPanel jPanelMenuJefeCentroComputo;
  // End of variables declaration//GEN-END:variables
}
