/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica.iniciarsesion;


import CentroComputo.Usuario;
import centrocomputo.interfaz.InventarioUsuarioInterface;


/**
 *
 * @author Alberto Sánchez
 */
public class VentanaIniciarSesion extends javax.swing.JFrame {
  
  
   private static VentanaIniciarSesion ventanaIniciarSesion = null;
   InventarioUsuarioInterface inventarioUsuario;

  /**
   * Creates new form VentanaIniciarSesion
   */
  
  public VentanaIniciarSesion(InventarioUsuarioInterface inventarioUsuario){
    this.inventarioUsuario = inventarioUsuario;
    this.ventanaIniciarSesion = ventanaIniciarSesion;
    initComponents();
    agregarCoso();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanelIniciarSesion = new javax.swing.JPanel();
    jLabelLogoCc = new javax.swing.JLabel();
    jLabelNombreUsuario = new javax.swing.JLabel();
    jLabelContrasenia = new javax.swing.JLabel();
    jTextFieldUsuario = new javax.swing.JTextField();
    jButtonIngresar = new javax.swing.JButton();
    jPasswordField2 = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setIconImage(getIconImage());
    setIconImages(null);
    setName("frameIniciarSesion"); // NOI18N

    jPanelIniciarSesion.setBackground(new java.awt.Color(255, 255, 255));

    jLabelLogoCc.setIcon(new javax.swing.ImageIcon("C:\\Users\\stamp.DESKTOP-QN6GH5L\\Dropbox\\Proyecto Construcción\\CentroComputo\\src\\interfazgrafica\\imagenes\\LabelLogoCc.png")); // NOI18N

    jLabelNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabelNombreUsuario.setText("Nombre de usuario:");

    jLabelContrasenia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabelContrasenia.setText("Contraseña:");

    jButtonIngresar.setText("Ingresar");
    jButtonIngresar.setBorder(null);

    jPasswordField2.setText("asdasdddddddddddddddddddsadad");

    javax.swing.GroupLayout jPanelIniciarSesionLayout = new javax.swing.GroupLayout(jPanelIniciarSesion);
    jPanelIniciarSesion.setLayout(jPanelIniciarSesionLayout);
    jPanelIniciarSesionLayout.setHorizontalGroup(
      jPanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelIniciarSesionLayout.createSequentialGroup()
        .addContainerGap(181, Short.MAX_VALUE)
        .addGroup(jPanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIniciarSesionLayout.createSequentialGroup()
            .addComponent(jLabelLogoCc)
            .addGap(147, 147, 147))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIniciarSesionLayout.createSequentialGroup()
            .addComponent(jLabelNombreUsuario)
            .addGap(217, 217, 217))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIniciarSesionLayout.createSequentialGroup()
            .addComponent(jLabelContrasenia)
            .addGap(249, 249, 249))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIniciarSesionLayout.createSequentialGroup()
            .addComponent(jButtonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(253, 253, 253))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIniciarSesionLayout.createSequentialGroup()
            .addGroup(jPanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(jTextFieldUsuario)
              .addComponent(jPasswordField2))
            .addGap(195, 195, 195))))
    );
    jPanelIniciarSesionLayout.setVerticalGroup(
      jPanelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelIniciarSesionLayout.createSequentialGroup()
        .addComponent(jLabelLogoCc, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabelNombreUsuario)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabelContrasenia)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(19, 19, 19)
        .addComponent(jButtonIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  public void agregarCoso(){
    
    Usuario man = new Usuario();
    man.setIdentificador("2313123");
    man.setNombres("Miguel Andrés");
    man.setApellido("Reyes Dominguez");
    man.setCorreoInstitucional("miguel@gmail.com");
    man.setContrasenia("zx123321xz");
    man.setRolTecnicoAcademico();
    man.setTelefonoConExtension("2282837485");
    this.inventarioUsuario.guardaUsuario(man);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonIngresar;
  private javax.swing.JLabel jLabelContrasenia;
  private javax.swing.JLabel jLabelLogoCc;
  private javax.swing.JLabel jLabelNombreUsuario;
  private javax.swing.JPanel jPanelIniciarSesion;
  private javax.swing.JPasswordField jPasswordField2;
  private javax.swing.JTextField jTextFieldUsuario;
  // End of variables declaration//GEN-END:variables
}
