/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica.administrarusuarios;

/**
 *
 * @author Alberto Sánchez
 */
public class VentanaAñadirUsuario extends javax.swing.JFrame {

  String rolNecesario = "JCC";
  
  /**
   * Creates new form VentanaAñadirUsuario
   */
  public VentanaAñadirUsuario() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabelEtiquetaAdministrarUsuarios = new javax.swing.JLabel();
    jPanelAñadir = new javax.swing.JPanel();
    jLabelNombre = new javax.swing.JLabel();
    jLabelApellido = new javax.swing.JLabel();
    jLabelNumeroPersonal = new javax.swing.JLabel();
    jLabelTelefono = new javax.swing.JLabel();
    jLabelCorreo = new javax.swing.JLabel();
    jTextFieldNombre = new javax.swing.JTextField();
    jTextFieldCorreo = new javax.swing.JTextField();
    jTextFieldNumeroPersonal = new javax.swing.JTextField();
    jButtonGuardar = new javax.swing.JButton();
    jTextFieldApellido = new javax.swing.JTextField();
    jLabelEtiquetaRegresar = new javax.swing.JLabel();
    jTextFieldTelefono = new javax.swing.JTextField();
    jLabelRegresar = new javax.swing.JLabel();
    jLabelEtiquetaAñadirUsuarios = new javax.swing.JLabel();

    jLabelEtiquetaAdministrarUsuarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabelEtiquetaAdministrarUsuarios.setText("Administrar Usuarios");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));

    jPanelAñadir.setBackground(new java.awt.Color(255, 255, 255));

    jLabelNombre.setText("Nombre(s):");

    jLabelApellido.setText("Apellido(s):");

    jLabelNumeroPersonal.setText("No. personal:");

    jLabelTelefono.setText("Telefono:");

    jLabelCorreo.setText("Correo:");

    jButtonGuardar.setText("Guardar");
    jButtonGuardar.setBorder(null);

    jLabelEtiquetaRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabelEtiquetaRegresar.setText("Regresar");

    jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazgrafica/imagenes/LabelBack.png"))); // NOI18N

    jLabelEtiquetaAñadirUsuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabelEtiquetaAñadirUsuarios.setText("Añadir técnico académico");

    javax.swing.GroupLayout jPanelAñadirLayout = new javax.swing.GroupLayout(jPanelAñadir);
    jPanelAñadir.setLayout(jPanelAñadirLayout);
    jPanelAñadirLayout.setHorizontalGroup(
      jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelAñadirLayout.createSequentialGroup()
        .addGroup(jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanelAñadirLayout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabelRegresar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabelEtiquetaRegresar))
          .addGroup(jPanelAñadirLayout.createSequentialGroup()
            .addGap(117, 117, 117)
            .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanelAñadirLayout.createSequentialGroup()
            .addGap(89, 89, 89)
            .addComponent(jLabelEtiquetaAñadirUsuarios))
          .addGroup(jPanelAñadirLayout.createSequentialGroup()
            .addGap(65, 65, 65)
            .addGroup(jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabelApellido)
              .addComponent(jLabelNombre)
              .addComponent(jLabelNumeroPersonal)
              .addComponent(jLabelTelefono)
              .addComponent(jLabelCorreo))
            .addGap(18, 18, 18)
            .addGroup(jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextFieldNumeroPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(81, Short.MAX_VALUE))
    );
    jPanelAñadirLayout.setVerticalGroup(
      jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelAñadirLayout.createSequentialGroup()
        .addGap(10, 10, 10)
        .addGroup(jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabelRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabelEtiquetaRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabelEtiquetaAñadirUsuarios)
        .addGap(32, 32, 32)
        .addGroup(jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelNombre))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelApellido)
          .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(14, 14, 14)
        .addGroup(jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jTextFieldNumeroPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelNumeroPersonal))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelTelefono)
          .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(11, 11, 11)
        .addGroup(jPanelAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelCorreo)
          .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(23, 23, 23))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanelAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonGuardar;
  private javax.swing.JLabel jLabelApellido;
  private javax.swing.JLabel jLabelCorreo;
  private javax.swing.JLabel jLabelEtiquetaAdministrarUsuarios;
  private javax.swing.JLabel jLabelEtiquetaAñadirUsuarios;
  private javax.swing.JLabel jLabelEtiquetaRegresar;
  private javax.swing.JLabel jLabelNombre;
  private javax.swing.JLabel jLabelNumeroPersonal;
  private javax.swing.JLabel jLabelRegresar;
  private javax.swing.JLabel jLabelTelefono;
  private javax.swing.JPanel jPanelAñadir;
  private javax.swing.JTextField jTextFieldApellido;
  private javax.swing.JTextField jTextFieldCorreo;
  private javax.swing.JTextField jTextFieldNombre;
  private javax.swing.JTextField jTextFieldNumeroPersonal;
  private javax.swing.JTextField jTextFieldTelefono;
  // End of variables declaration//GEN-END:variables
}
