/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica.administrarusuarios;

/**
 *
 * @author Alberto Sánchez
 */
public class VentanaVisualizarUsuario extends javax.swing.JFrame {
  
  String rolNecesario = "JCC";

  /**
   * Creates new form VentanaVisualizarUsuario
   */
  public VentanaVisualizarUsuario() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel5 = new javax.swing.JLabel();
    jPanelVisualizar = new javax.swing.JPanel();
    jLabelEtiquetaRegresar = new javax.swing.JLabel();
    jLabelRegresar = new javax.swing.JLabel();
    jLabelEtiquetaVisualizarTecnicoAcademico = new javax.swing.JLabel();
    jLabelNombre = new javax.swing.JLabel();
    jLabelApellido = new javax.swing.JLabel();
    jLabelNumeroPersonal = new javax.swing.JLabel();
    jLabelTelefono = new javax.swing.JLabel();
    jLabelCorreo = new javax.swing.JLabel();
    jLabelVisualizarNombre = new javax.swing.JLabel();
    jLabelVisualizarApellido = new javax.swing.JLabel();
    jLabelVisualizarNumeroPersonal = new javax.swing.JLabel();
    jLabelVisualizarTelefono = new javax.swing.JLabel();
    jLabelVisualizarCorreo = new javax.swing.JLabel();

    jLabel5.setText("jLabel5");

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanelVisualizar.setBackground(new java.awt.Color(255, 255, 255));

    jLabelEtiquetaRegresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabelEtiquetaRegresar.setText("Regresar");

    jLabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazgrafica/imagenes/LabelBack.png"))); // NOI18N

    jLabelEtiquetaVisualizarTecnicoAcademico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabelEtiquetaVisualizarTecnicoAcademico.setText("Visualizar técnico académico");

    jLabelNombre.setText("Nombre(s):");

    jLabelApellido.setText("Apellido(s):");

    jLabelNumeroPersonal.setText("No. personal:");

    jLabelTelefono.setText("Telefono:");

    jLabelCorreo.setText("Correo:");

    jLabelVisualizarNombre.setText("EntradaNombre");

    jLabelVisualizarApellido.setText("EntradaApellido");

    jLabelVisualizarNumeroPersonal.setText("EntradaNumeroPersonal");

    jLabelVisualizarTelefono.setText("EntradaTelefono");

    jLabelVisualizarCorreo.setText("EntradaCorreo");

    javax.swing.GroupLayout jPanelVisualizarLayout = new javax.swing.GroupLayout(jPanelVisualizar);
    jPanelVisualizar.setLayout(jPanelVisualizarLayout);
    jPanelVisualizarLayout.setHorizontalGroup(
      jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelVisualizarLayout.createSequentialGroup()
        .addGroup(jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanelVisualizarLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabelRegresar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabelEtiquetaRegresar))
          .addGroup(jPanelVisualizarLayout.createSequentialGroup()
            .addGap(109, 109, 109)
            .addGroup(jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabelEtiquetaVisualizarTecnicoAcademico)
              .addGroup(jPanelVisualizarLayout.createSequentialGroup()
                .addGroup(jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanelVisualizarLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jLabelNombre))
                  .addGroup(jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelApellido)
                    .addComponent(jLabelNumeroPersonal))
                  .addGroup(jPanelVisualizarLayout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                      .addComponent(jLabelTelefono)
                      .addComponent(jLabelCorreo))))
                .addGap(37, 37, 37)
                .addGroup(jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabelVisualizarNombre)
                  .addComponent(jLabelVisualizarApellido)
                  .addComponent(jLabelVisualizarNumeroPersonal)
                  .addComponent(jLabelVisualizarTelefono)
                  .addComponent(jLabelVisualizarCorreo))))))
        .addContainerGap(72, Short.MAX_VALUE))
    );
    jPanelVisualizarLayout.setVerticalGroup(
      jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelVisualizarLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabelEtiquetaRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelRegresar))
        .addGap(10, 10, 10)
        .addComponent(jLabelEtiquetaVisualizarTecnicoAcademico)
        .addGap(18, 18, 18)
        .addGroup(jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelNombre)
          .addComponent(jLabelVisualizarNombre))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelApellido)
          .addComponent(jLabelVisualizarApellido))
        .addGap(14, 14, 14)
        .addGroup(jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelNumeroPersonal)
          .addComponent(jLabelVisualizarNumeroPersonal))
        .addGap(18, 18, 18)
        .addGroup(jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelTelefono)
          .addComponent(jLabelVisualizarTelefono))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanelVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelCorreo)
          .addComponent(jLabelVisualizarCorreo))
        .addContainerGap(54, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanelVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VentanaVisualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VentanaVisualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VentanaVisualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VentanaVisualizarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VentanaVisualizarUsuario().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabelApellido;
  private javax.swing.JLabel jLabelCorreo;
  private javax.swing.JLabel jLabelEtiquetaRegresar;
  private javax.swing.JLabel jLabelEtiquetaVisualizarTecnicoAcademico;
  private javax.swing.JLabel jLabelNombre;
  private javax.swing.JLabel jLabelNumeroPersonal;
  private javax.swing.JLabel jLabelRegresar;
  private javax.swing.JLabel jLabelTelefono;
  private javax.swing.JLabel jLabelVisualizarApellido;
  private javax.swing.JLabel jLabelVisualizarCorreo;
  private javax.swing.JLabel jLabelVisualizarNombre;
  private javax.swing.JLabel jLabelVisualizarNumeroPersonal;
  private javax.swing.JLabel jLabelVisualizarTelefono;
  private javax.swing.JPanel jPanelVisualizar;
  // End of variables declaration//GEN-END:variables
}
