/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazgrafica.administrarhardware;

import CentroComputo.*;
import centrocomputo.interfaz.*;
import java.text.*;
import javax.swing.*;

/**
 *
 * @author Alberto Sánchez
 */
public class VentanaVisualizarHardware extends javax.swing.JFrame {
  
  InventarioHardwareInterface inventarioHardware;
  VentanaAdministrarHardware ventanaCrudHardware = null;
  private String identificadorFila = null;
  String rolNecesario = "JCC";

  /**
   * Creates new form VentanaVisualizarHardware
   */
   VentanaVisualizarHardware(VentanaAdministrarHardware ventanaCrudHardware, InventarioHardwareInterface inventarioHardware) {
    this.inventarioHardware = inventarioHardware;
    this.ventanaCrudHardware = ventanaCrudHardware;
    identificadorFila = ventanaCrudHardware.getIdentificadorFila();
     initComponents();
     despliegaHardware();
  }

  public void setjLabelVisualizarAdquisicion(String fechaAdquisicion) {
    this.jLabelVisualizarAdquisicion.setText(fechaAdquisicion);
  }

  public void setjLabelVisualizarMarca(String marca) {
    this.jLabelVisualizarMarca.setText(marca);
  }

  public void setjLabelVisualizarModelo(String modelo) {
    this.jLabelVisualizarModelo.setText(modelo);
  }

  public void setjLabelVisualizarNumeroInventario(String numeroInventario) {
    this.jLabelVisualizarNumeroInventario.setText(numeroInventario);
  }

  public void setjLabelVisualizarNumeroSerie(String numeroSerie) {
    this.jLabelVisualizarNumeroSerie.setText(numeroSerie);
  }

  public void setjLabelVisualizarPartes(String partes) {
    this.jLabelVisualizarPartes.setText(partes);
  }

  public void setjLabelVisualizarTipo(String tipo) {
    this.jLabelVisualizarTipo.setText(tipo);
  }

  public void setjLabelVisualizarUbicacion(String ubicacion) {
    this.jLabelVisualizarUbicacion.setText(ubicacion);
  }

  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanelVisualizarr = new javax.swing.JPanel();
    jLabelRegresar1 = new javax.swing.JLabel();
    jLabelEtiquetaRegresar1 = new javax.swing.JLabel();
    jLabelEtiquetaVisualizarHardware = new javax.swing.JLabel();
    jLabelNumeroInventario = new javax.swing.JLabel();
    jLabelMarca = new javax.swing.JLabel();
    jLabelTipo = new javax.swing.JLabel();
    jLabelFecha = new javax.swing.JLabel();
    jLabelTipo2 = new javax.swing.JLabel();
    jLabelModelo = new javax.swing.JLabel();
    jLabelNumeroSerie = new javax.swing.JLabel();
    jLabelUbicacion = new javax.swing.JLabel();
    jLabelPartes = new javax.swing.JLabel();
    jLabelVisualizarNumeroInventario = new javax.swing.JLabel();
    jLabelVisualizarMarca = new javax.swing.JLabel();
    jLabelVisualizarTipo = new javax.swing.JLabel();
    jLabelVisualizarAdquisicion = new javax.swing.JLabel();
    jLabelVisualizarModelo = new javax.swing.JLabel();
    jLabelVisualizarNumeroSerie = new javax.swing.JLabel();
    jLabelVisualizarUbicacion = new javax.swing.JLabel();
    jLabelVisualizarPartes = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanelVisualizarr.setBackground(new java.awt.Color(255, 255, 255));

    jLabelRegresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazgrafica/imagenes/LabelBack.png"))); // NOI18N
    jLabelRegresar1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jLabelRegresar1MouseClicked(evt);
      }
    });

    jLabelEtiquetaRegresar1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabelEtiquetaRegresar1.setText("Regresar");

    jLabelEtiquetaVisualizarHardware.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabelEtiquetaVisualizarHardware.setText("Visualizar hardware");

    jLabelNumeroInventario.setText("No. inventario:");

    jLabelMarca.setText("Marca:");

    jLabelTipo.setText("Tipo:");

    jLabelFecha.setText("Fecha Adquisición:");

    jLabelModelo.setText("Modelo:");

    jLabelNumeroSerie.setText("No. serie:");

    jLabelUbicacion.setText("Ubicacion:");

    jLabelPartes.setText("Partes:");

    jLabelVisualizarNumeroInventario.setText("EntradaInventario");

    jLabelVisualizarMarca.setText("EntradaMarca");

    jLabelVisualizarTipo.setText("EntradaTipo");

    jLabelVisualizarAdquisicion.setText("EntradaFechaAdquisicion");

    jLabelVisualizarModelo.setText("EntradaModelo");

    jLabelVisualizarNumeroSerie.setText("EntradaNumeroSerie");

    jLabelVisualizarUbicacion.setText("EntradaUbicacion");

    jLabelVisualizarPartes.setText("EntradaPartes");

    javax.swing.GroupLayout jPanelVisualizarrLayout = new javax.swing.GroupLayout(jPanelVisualizarr);
    jPanelVisualizarr.setLayout(jPanelVisualizarrLayout);
    jPanelVisualizarrLayout.setHorizontalGroup(
      jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanelVisualizarrLayout.createSequentialGroup()
        .addGap(42, 42, 42)
        .addGroup(jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabelTipo)
            .addComponent(jLabelMarca)
            .addComponent(jLabelFecha, javax.swing.GroupLayout.Alignment.LEADING))
          .addComponent(jLabelNumeroInventario, javax.swing.GroupLayout.Alignment.TRAILING))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelVisualizarAdquisicion)
          .addComponent(jLabelVisualizarMarca)
          .addComponent(jLabelVisualizarNumeroInventario)
          .addComponent(jLabelVisualizarTipo))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
        .addGroup(jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabelUbicacion, javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVisualizarrLayout.createSequentialGroup()
              .addGap(2, 2, 2)
              .addComponent(jLabelNumeroSerie))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelVisualizarrLayout.createSequentialGroup()
              .addGap(11, 11, 11)
              .addComponent(jLabelModelo)))
          .addComponent(jLabelPartes, javax.swing.GroupLayout.Alignment.TRAILING))
        .addGap(0, 21, Short.MAX_VALUE)
        .addGroup(jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelVisualizarUbicacion)
          .addComponent(jLabelVisualizarPartes)
          .addComponent(jLabelVisualizarModelo)
          .addComponent(jLabelVisualizarNumeroSerie))
        .addGap(44, 44, 44))
      .addGroup(jPanelVisualizarrLayout.createSequentialGroup()
        .addGap(18, 18, 18)
        .addComponent(jLabelRegresar1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabelTipo2)
          .addComponent(jLabelEtiquetaRegresar1))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVisualizarrLayout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jLabelEtiquetaVisualizarHardware)
        .addGap(168, 168, 168))
    );
    jPanelVisualizarrLayout.setVerticalGroup(
      jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVisualizarrLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabelRegresar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabelEtiquetaRegresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(2, 2, 2)
        .addComponent(jLabelEtiquetaVisualizarHardware)
        .addGap(29, 29, 29)
        .addGroup(jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelNumeroInventario)
          .addComponent(jLabelModelo)
          .addComponent(jLabelVisualizarNumeroInventario)
          .addComponent(jLabelVisualizarModelo))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabelNumeroSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelVisualizarNumeroSerie))
          .addGroup(jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabelMarca)
            .addComponent(jLabelVisualizarMarca)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelUbicacion)
          .addComponent(jLabelVisualizarUbicacion)
          .addComponent(jLabelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabelVisualizarAdquisicion))
        .addGap(16, 16, 16)
        .addGroup(jPanelVisualizarrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabelTipo)
          .addComponent(jLabelVisualizarTipo)
          .addComponent(jLabelPartes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabelVisualizarPartes))
        .addGap(69, 69, 69)
        .addComponent(jLabelTipo2)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 536, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanelVisualizarr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 247, Short.MAX_VALUE)
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanelVisualizarr, javax.swing.GroupLayout.PREFERRED_SIZE, 247, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jLabelRegresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegresar1MouseClicked
    regresaVentana();
  }//GEN-LAST:event_jLabelRegresar1MouseClicked

  
  private void regresaVentana() {
    this.setVisible(false);
    this.dispose();
    this.ventanaCrudHardware.setVisible(true);
  }
   
  private void despliegaHardware() {
    if (!recuperaHardware()) {
      JOptionPane.showMessageDialog(VentanaVisualizarHardware.this,
              "No se ha podido recuperar la información del hardware ", "Advertencia", JOptionPane.ERROR_MESSAGE);
    }
  }
    
  private boolean recuperaHardware() {
     SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy/MM/dd");
    Hardware hardware = VentanaVisualizarHardware.this.inventarioHardware.buscaHardware(identificadorFila);
    if (hardware != null|| hardware.getFechaAdquisicion()!=null) {
      String fechaComoCadena = formatoFecha.format(hardware.getFechaAdquisicion());
      this.setjLabelVisualizarAdquisicion(fechaComoCadena);
      this.setjLabelVisualizarMarca(hardware.getMarca());
      this.setjLabelVisualizarModelo(hardware.getModelo());
      this.setjLabelVisualizarNumeroInventario(hardware.getNumeroInventario());
      this.setjLabelVisualizarNumeroSerie(hardware.getNumeroSerie());
      this.setjLabelVisualizarPartes(hardware.getPartesdispositivo());
      this.setjLabelVisualizarTipo(hardware.getTipoDispositivo());
      this.setjLabelVisualizarUbicacion(hardware.getUbicacion());
      return true;
    }
    return false;
  }
 
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabelEtiquetaRegresar1;
  private javax.swing.JLabel jLabelEtiquetaVisualizarHardware;
  private javax.swing.JLabel jLabelFecha;
  private javax.swing.JLabel jLabelMarca;
  private javax.swing.JLabel jLabelModelo;
  private javax.swing.JLabel jLabelNumeroInventario;
  private javax.swing.JLabel jLabelNumeroSerie;
  private javax.swing.JLabel jLabelPartes;
  private javax.swing.JLabel jLabelRegresar1;
  private javax.swing.JLabel jLabelTipo;
  private javax.swing.JLabel jLabelTipo2;
  private javax.swing.JLabel jLabelUbicacion;
  private javax.swing.JLabel jLabelVisualizarAdquisicion;
  private javax.swing.JLabel jLabelVisualizarMarca;
  private javax.swing.JLabel jLabelVisualizarModelo;
  private javax.swing.JLabel jLabelVisualizarNumeroInventario;
  private javax.swing.JLabel jLabelVisualizarNumeroSerie;
  private javax.swing.JLabel jLabelVisualizarPartes;
  private javax.swing.JLabel jLabelVisualizarTipo;
  private javax.swing.JLabel jLabelVisualizarUbicacion;
  private javax.swing.JPanel jPanelVisualizarr;
  // End of variables declaration//GEN-END:variables
}
